using System;
using System.Linq;

using Leap;

namespace IUtilMusic.Listeners
{
    /// <summary>
    /// Listener of data generated by the Leap Motion device
    /// </summary>
    public class LeapMotionListener
    {
        #region Members
        /// <summary>
        /// Instance of gestures's listener
        /// </summary>
        private GestureListener _gestureListener; 
        #endregion

        #region Constructors
        /// <summary>
        /// Listener of data generated by the Leap Motion device 
        /// </summary>
        public LeapMotionListener()
        {
            this._gestureListener = new GestureListener();
        } 
        #endregion

        #region Public Events
        /// <summary>
        /// Event dispatched when the application has successfully 
        /// connected to the Leap Motion device
        /// </summary>
        /// <param name="sender">Controller whom executed this event</param>
        /// <param name="args">Arguments concerning the connection</param>
        /// <remarks>Represent Controller.Connect</remarks>
        public void OnServiceConnect(object sender, ConnectionEventArgs args)
        {
            Console.WriteLine("Service Connected");
        }

        /// <summary>
        /// Event dispatched when Leap motion device become available 
        /// (Either after the Connect event or when device plugged in)
        /// </summary>
        /// <param name="sender">Controller whom executed this event</param>
        /// <param name="args">Arguments concerning the device</param>
        /// <remarks>Represent Controller.Device</remarks>
        public void OnConnect(object sender, DeviceEventArgs args)
        {
            Console.WriteLine("Connected");

        }

        /// <summary>
        /// Event dispatched when a new tracking frame is available
        /// </summary>
        /// <param name="sender">Controller whom executed this event</param>
        /// <param name="args">Arguments concerning the current frame</param>
        /// <remarks>Represent Controller.FrameReady</remarks>
        public void OnFrame(object sender, FrameEventArgs args)
        {
            //Get the most recent frame and report some basic information
            Frame frame = args.frame;

            bool isValid = frame.Hands.Count() > 0;
            if (isValid)
            {
                _gestureListener.RegisterFrame(frame);
                _gestureListener.ExecuteEvent();
            }
        } 
        #endregion
    }
}

